services:
  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - 3306
      - 33060
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
      - ../special-gallery:/var/www/html/wp-content/plugins/special-gallery:rw

  wordpress-cli:
    image: wordpress:cli
    depends_on:
      - wordpress
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    # vstm: This is required to run wordpress-cli with the same
    # user-id as wordpress. This way there are no permission problems
    # when running the cli
    user: '33'
    command: /tmp/wp-setup.sh
    volumes:
      - wp_data:/var/www/html  # This volume must match the one in the 'wordpress' service
      - ./wordpress/wp-setup.sh:/tmp/wp-setup.sh
volumes:
  db_data:
  wp_data: